// Generated by https://quicktype.io

export interface PlacesResponse {
  type: string;
  query: number[];
  features: Feature[];
  attribution: string;
}

export interface Feature {
  id: string;
  type: string;
  place_type: string[];
  relevance: number;
  properties: Properties;
  text_en: string;
  place_name_en: string;
  text: string;
  place_name: string;
  center: number[];
  geometry: Geometry;
  context?: Context[];
  bbox?: number[];
  language_en?: Language;
  language?: Language;
}

export interface Context {
  id: string;
  mapbox_id: string;
  text_en: string;
  text: string;
  wikidata?: string;
  language_en?: Language;
  language?: Language;
  short_code?: string;
}

export enum Language {
  En = "en",
}

export interface Geometry {
  coordinates: number[];
  type: string;
}

export interface Properties {
  foursquare?: string;
  landmark?: boolean;
  address?: string;
  category?: string;
  mapbox_id?: string;
  wikidata?: string;
  short_code?: string;
}
